apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: todonodejs
    app.kubernetes.io/part-of: mysql
    name: frontend
  name: frontend
spec:
  host: todo.apps.ocp4.example.com
  path: /todo
  to:
    kind: Service
    name: frontend
    weight: 100
  wildcardPolicy: None
